config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


  get "/" => "homes#top", as: "top"
  get "/about" => "homes#about", as: "about"
  get "/customers" => "customer/customers#rule", as: "customer_rule"

  namespace :admin do

    resources:orders,only:[:index,:show,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:genres,only:[:index,:create,:edit,:update]
    resources:items,only:[:index,:new,:create,:show,:edit,:update]

    root to:'homes#top'
  end

  namespace :public do
    # post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get "confirm"
        get "complete"
      end
    end
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete "cart_items/destroy_all" => "cart_items#all_destroy", as: "cart_item_all_destroy"
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]

    get 'customers/information/edit'=>'customers#edit',as: 'customer_edit'
    patch "update" => "customers#update", as: "customer_update"
    get 'customers/my_page'=>'customers#show',as: 'my_page'
    get "customers/unsubscribe" => "customers#unsubscribe", as: "customer_unsubscribe"
    patch "withdraw" => "customers#withdraw", as: "customer_withdraw"
    root to:'homes#top'
    get 'homes/about'
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
         
  def full_name
    self.last_name + self.first_name
  end
  
  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end
  
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true, numericality: { only_integer: true }, length: { is: 7 }
  validates :address, presence: true
  validates :telephone_number, presence: true, numericality: { only_integer: true }
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  
  
  def index
    @customers=Customer.page(params[:page]).per(10)
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    @customer=Customer.find(params[:id])
    @customer.update(customer_params)
    render action: :show
  end
  
  private
  
  def customers_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:encrypted_password,:postal_code,:address,:telephone_number,:is_active)  
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="admin-customer-edit pt-5">

  <h4 class="alert alert-secondary" role="alert"><%= @customer.full_name %>さんの会員情報編集</h4>
    <%= form_with(model: @customer, url: admin_customer_path(@customer), local: true) do |f| %>
      <table class="w-100 admin-customer-show">
        <tr class="row pb-3">
          <td class="col-md-2">会員ID</td>
          <td class="col-md-10"><%= @customer.id %></td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">氏名</td>
          <td class="col-md-10">
            <%= f.text_field :last_name, class: "mr-4" %>
            <%= f.text_field :first_name %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">フリガナ</td>
          <td class="col-md-10">
            <%= f.text_field :last_name_kana, class: "mr-4" %>
            <%= f.text_field :first_name_kana %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">郵便番号</td>
          <td class="col-md-10">
            <%= f.text_field :postal_code %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">住所</td>
          <td class="col-md-6">
            <%= f.text_field :address, class: "w-100" %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">電話番号</td>
          <td class="col-md-10">
            <%= f.text_field :telephone_number %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">メールアドレス</td>
          <td class="col-md-10">
            <%= f.email_field :email %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">会員ステータス</td>
          <td class="col-md-10">
            <span class="admin-is_active-radio_button mr-3">
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, '退会', value: true %>
            </span>
            <span class="admin-is_active-radio_button">
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, '有効', value: false %>
            </span>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2"></td>
          <td class="col-md-10">
            <%= f.submit "変更を保存", class: "btn btn-success" %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="admin-customer pt-5">
    <h4 class="alert alert-secondary  col-2" role="alert">会員一覧</h4>
    <table class="table">
      <tr class="table-active">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
      <% @customers.each do |customer| %>
        <tr>
          <td>
            <%= customer.id %>
          </td>
          <td>
            <%= link_to customer.full_name, admin_customer_path(customer), class: "text-dark" %>
          </td>
          <td>
            <%= customer.email %>
          </td>
          <td>
            <% if customer.is_active == true %>
              <p class="text-secondary">退会</p>
            <% else %>
              <p class="text-success">有効</p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
    <div class="pagenate">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="admin-customer-show pt-5">
    <h4 class="alert alert-secondary" role="alert"><%= @customer.full_name %>さんの会員詳細</h4>
    <table class="w-100 admin-customer-show">
      <tr class="row pb-3">
        <td class="col-md-2">会員ID</td>
        <td class="col-md-10"><%= @customer.id %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">氏名</td>
        <td class="col-md-10"><%= @customer.full_name %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">フリガナ</td>
        <td class="col-md-10"><%= @customer.full_name_kana %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">郵便番号</td>
        <td class="col-md-10"><%= @customer.postal_code %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">住所</td>
        <td class="col-md-10"><%= @customer.address %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">電話番号</td>
        <td class="col-md-10"><%= @customer.telephone_number %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">メールアドレス</td>
        <td class="col-md-10"><%= @customer.email %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">会員ステータス</td>
        <td class="col-md-10">
          <% if @customer.is_active == true %>
            <p class="text-secondary">退会済</p>
          <% else %>
            <p class="text-success">有効</p>
          <% end %>
        </td>
      </tr>
      <tr class="row">
        <td class="col-md-2"></td>
        <td class="col-md-10">
          <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success mr-5", type: "button" %>
          <%= link_to "注文履歴一覧を見る", admin_path(@customer), class: "btn btn-info", type: "button" %>
        </td>
      </tr>
    </table>
  </div>
</div>