config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


  get "/" => "homes#top", as: "top"
  get "/about" => "homes#about", as: "about"
  get "/customers" => "customer/customers#rule", as: "customer_rule"

  namespace :admin do

    resources:orders,only:[:index,:show,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:genres,only:[:index,:create,:edit,:update]
    resources:items,only:[:index,:new,:create,:show,:edit,:update]

    root to:'homes#top'
  end

  namespace :public do
    # post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get "confirm"
        get "complete"
      end
    end
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete "cart_items/destroy_all" => "cart_items#all_destroy", as: "cart_item_all_destroy"
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]

    get 'customers/information/edit'=>'customers#edit',as: 'customer_edit'
    patch "update" => "customers#update", as: "customer_update"
    get 'customers/my_page'=>'customers#show',as: 'my_page'
    get "customers/unsubscribe" => "customers#unsubscribe", as: "customer_unsubscribe"
    patch "withdraw" => "customers#withdraw", as: "customer_withdraw"
    root to:'homes#top'
    get 'homes/about'
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord

    has_many :order_details, dependent: :destroy
    belongs_to :customer

    # 注文の全ての数量合計
    def sum_order_items
        self.item_orders.all.sum(:amount)
    end
    
    #注文の合計金額
    def total_price
        array = []
        self.order_details.each do |order_detail|
           array << order_detail.tax_price * order_detail.amount
       end
        array.sum
    end
    
    enum payment_method:{credit_card:0,transfer:1}
    # enum select_address:{customer_address:0,registered_address:1,new_address:2}
    enum order_status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4}
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  
  
  def index
    @orders = Order.page(params[:page]).per(10)
  end
  
  def show
    @order=Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details= @order.order_details
    @order.update(order_params)
    if @order.order_status === "入金確認"
      order_details.each do |order_detail|
        order_detail.update(order_detail_params)
      end
    end
    @orders = Order.page(params[:page]).per(10)
    redirect_to admin_orders_path
  end

  
  
  private

    def order_detail_params
      params.permit(:is_active).merge(is_active: 1)
    end

    def order_params
      params.require(:order).permit(:is_active).merge(is_active: params[:order][:is_active].to_i)
    end
  
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="admin-order-index pt-5">
    <h4 class="pb-3">注文履歴一覧</h4>
    <table class="table">
      <tr class="table-active">
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to admin_order_path(order), class: "text-dark" do %>
              <%= l order.created_at %>
            <% end %>
          </td>
          <td>
            <%= order.customer.full_name %>
          </td>
          <td>
            <%= order.sum_order_items.to_s(:delimited) %>
          </td>
          <td>
            <%= order.order_status %>
          </td>
        </tr>
      <% end %>
    </table>
    <div class="pagenate">
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="admin-order-show pt-5">
    <h4 class="pb-3">注文履歴一覧</h4>
    <table class="w-100 admin-order-details admin-customer-show">
      <tr class="row pb-2">
        <th class="col-md-2">購入者</th>
        <td class="col-md-10">
          <%= link_to @order.customer.full_name, admin_customer_path(@order.customer), class: "text-dark" %>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">注文日</th>
        <td class="col-md-10">
          <%= l @order.created_at, format: :short %>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">配送先</th>
        <td class="col-md-10">
          <div class="admin-order-post mb-2">
            <span>
              〒<%= @order.postcode.to_s.insert(3, "-") %>
            </span>
            <span>
              <%= @order.address %>
            </span>
          </div>
          <div class="admin-order-post">
            <%= @order.destination %>
          </div>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">支払方法</th>
        <td class="col-md-10">
          <%= @order.payment %>
        </td>
      </tr>
      <tr class="row pb-2">
        <th class="col-md-2">注文ステータス</th>
        <td class="col-md-10">
          <%= form_with model: @order, url: admin_order_path(@order), local: true do |f| %>
            <%= f.select :order_status, options_for_select(Order.order_statuses, selected: Order.order_statuses[@order.order_status]) %>
            <%= f.submit "更新", class: "btn btn-success ml-4"%>
          <% end %>
        </td>
      </tr>
    </table>

    <div class="admin-order-bottom row mt-5 w-100">
      <table class="table admin-order-items col-md-8">
        <tr>
          <th class="table-active">商品名</th>
          <th class="table-active">単価（税込）</th>
          <th class="text-center table-active">数量</th>
          <th class="text-center table-active">小計</th>
          <th class="table-active">製作ステータス</th>
        </tr>
        <% @order.item_orders.each do |item_order| %>
          <tr>
            <td><%= item_order.item.name %></td>
            <td><%= item_order.tax_price.to_s(:delimited) %></td>
            <td class="text-center"><%= item_order.quantity.to_s(:delimited) %></td>
            <td class="text-center"><%= (item_order.tax_price.to_i * item_order.quantity.to_i).to_s(:delimited) %></td>
            <td>
              <%= form_with model: item_order, url: admin_item_order_path(item_order), local: true do |f| %>
                <%= f.select :maiking_status, options_for_select(ItemOrder.maiking_statuses, selected: ItemOrder.maiking_statuses[item_order.maiking_status]) %>
                <%= f.submit "更新", class: "btn btn-success ml-3" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <table class="admin-order-details col-md-3 ml-auto mt-auto admin-customer-show">
        <tr>
          <th>商品合計</th>
          <td class="text-right"><%= @order.total_price.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td class="text-right"><%= @order.postage.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td class="text-right"><%= (@order.total_price.to_i + @order.postage.to_i).to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>