config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


  get "/" => "homes#top", as: "top"
  get "/about" => "homes#about", as: "about"
  get "/customers" => "customer/customers#rule", as: "customer_rule"

  namespace :admin do

    resources:orders,only:[:index,:show,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:genres,only:[:index,:create,:edit,:update]
    resources:items,only:[:index,:new,:create,:show,:edit,:update]

    root to:'homes#top'
  end

  namespace :public do
    # post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get "confirm"
        get "complete"
      end
    end
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete "cart_items/destroy_all" => "cart_items#all_destroy", as: "cart_item_all_destroy"
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]

    get 'customers/information/edit'=>'customers#edit',as: 'customer_edit'
    patch "update" => "customers#update", as: "customer_update"
    get 'customers/my_page'=>'customers#show',as: 'my_page'
    get "customers/unsubscribe" => "customers#unsubscribe", as: "customer_unsubscribe"
    patch "withdraw" => "customers#withdraw", as: "customer_withdraw"
    root to:'homes#top'
    get 'homes/about'
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/genre.rb
class Genre < ApplicationRecord
  
    has_many :items, dependent: :destroy
    validates :name, presence: true
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  
  
  def index
    @genres=Genre.all
    @genre=Genre.new
  end

  def create
    @genre=Genre.new(genre_params)
    if @genre.save
       flash[:notice] = "You have created Genre successfully"
       redirect_to admin_genres_path
    else
       @genres = Genre.all
       render :index
    end
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
    @genre=Genre.find(params[:id])
    if @genre.update(genre_params)
       flash[:notice] = "You have update Genre successfully"
       redirect_to admin_genres_path
    else
       render :edit
    end
  end
  
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="text-danger">
  <% if @genre.errors.any? %>
     <span class="h4"><%= @genre.errors.count %>errors prohibited this obj from being saved:</span>
    <% @genre.errors.full_messages.each do |message| %><br>
       ・<%= message %>
    <% end %>
  <% end %>
  </div>
  
  <h3 class="alert alert-secondary mb-5 col-2" role="alert">ジャンル編集</h3>
  <%= form_with model: @genre, url: admin_genre_path, local: true do |f| %>
  
  <p>ジャンル名 
    <span class="ml-4"><%= f.text_field :name %></span> 
    <span class="ml-4"><%= f.submit '変更を保存', class: "glyphicon glyphicon-pencil btn btn-success" %></span>
  </p>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="text-danger">
<% if @genre.errors.any? %>
   <span class="h4"><%= @genre.errors.count %>errors prohibited this obj from being saved:</span>
  <% @genre.errors.full_messages.each do |message| %><br>
     ・<%= message %>
  <% end %>
<% end %>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h3 class="col-3 alert alert-secondary" role="alert">ジャンル一覧・追加</h3>
      <%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
        <p class="mb-5">ジャンル名 <%= f.text_field :name %> <%= f.submit '新規登録', class: "glyphicon glyphicon-pencil btn btn-success" %></p>
      <% end %>
      <div class="col-xs-8 col-xs-offset-2">
        <table class="table">
          <thead>
            <tr>
              <th class="table-active">ジャンル</th>
              <th class="table-active"></th>
            <tr/>
          </thead>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "glyphicon glyphicon-pencil btn btn-success" %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>