config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


  get "/" => "homes#top", as: "top"
  get "/about" => "homes#about", as: "about"
  get "/customers" => "customer/customers#rule", as: "customer_rule"

  namespace :admin do

    resources:orders,only:[:index,:show,:update]
    resources:customers,only:[:index,:show,:edit,:update]
    resources:genres,only:[:index,:create,:edit,:update]
    resources:items,only:[:index,:new,:create,:show,:edit,:update]

    root to:'homes#top'
  end

  namespace :public do
    # post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get "confirm"
        get "complete"
      end
    end
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete "cart_items/destroy_all" => "cart_items#all_destroy", as: "cart_item_all_destroy"
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]

    get 'customers/information/edit'=>'customers#edit',as: 'customer_edit'
    patch "update" => "customers#update", as: "customer_update"
    get 'customers/my_page'=>'customers#show',as: 'my_page'
    get "customers/unsubscribe" => "customers#unsubscribe", as: "customer_unsubscribe"
    patch "withdraw" => "customers#withdraw", as: "customer_withdraw"
    root to:'homes#top'
    get 'homes/about'
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, presence: true, numericality: { only_integer: true }, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true
    
	# order/newで使用
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, numericality: { only_integer: true }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
         
  def full_name
    self.last_name + self.first_name
  end
  
  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end
  
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true, numericality: { only_integer: true }, length: { is: 7 }
  validates :address, presence: true
  validates :telephone_number, presence: true, numericality: { only_integer: true }
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  
    has_many :items, dependent: :destroy
    validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_one_attached:image
  
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  
  belongs_to:genre
  
  validates :genre_id, :name, :price, presence: true
  validates :introduction, length: {maximum: 200}
  validates :price, numericality: { only_integer: true }
  
end

app/models/order.rb
class Order < ApplicationRecord

    has_many :order_details, dependent: :destroy
    belongs_to :customer

    # 注文の全ての数量合計
    def sum_order_items
        self.item_orders.all.sum(:amount)
    end
    
    #注文の合計金額
    def total_price
        array = []
        self.order_details.each do |order_detail|
           array << order_detail.tax_price * order_detail.amount
       end
        array.sum
    end
    
    enum payment_method:{credit_card:0,transfer:1}
    # enum select_address:{customer_address:0,registered_address:1,new_address:2}
    enum order_status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4}
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  def subtotal
    purchase_price*amount
  end
  
  belongs_to :item
	belongs_to :order
	
	enum maiking_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
 
  
  def top
   @orders = Order.page(params[:page]).per(10)
  end
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action:configure_permitted_parameters,if: :devise_controller?
  
  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_items_path
    else
      public_my_page_path
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      new_customer_session_path
    end
  end
  
  def customer_shut_out
    unless admin_signed_in?
      redirect_to top_path
    end
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
  end
  
  def about
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def tax_price(price)
    (price * 1.1).floor
  end

  def sub_price(sub)
    (tax_price(sub.item.price) * sub.amount)
  end

  def total_price(totals)
    price = 0
    totals.each do |total|
      price += sub_price(total)
    end
    return price
  end
  
  def current_cart
    @cart_items = current_customer.cart_items
  end
  
  
  
  
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <span>Nagano Cake</span>
          </a>
          <div class="navbar navbar-light bg-light" id="navbarNavDropdown">
             <div class="container-fluid justify-content-end">
              <% if customer_signed_in? %>
                <div class="customer-name me-5 mt-5">
                  ようこそ、<%= current_customer.last_name %> さん!
                </div>
                <button class="btn btn-sm btn-outline-secondary me-5 ms-5" type="button">
                  <%= link_to "マイページ", public_my_page_path%>
                </button>
                <button class="btn btn-sm btn-outline-secondary me-5" type="button">
                  <%= link_to "商品一覧", public_items_path%>
                </button>
                <button class="btn btn-sm btn-outline-secondary me-5" type="button">
                  <%= link_to "カート",public_cart_items_path %>
                </button>
                <button class="btn btn-sm btn-outline-secondary me-5" type="button">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
                </button>
              <% elsif admin_signed_in? %>
                <button class="btn btn-sm btn-outline-secondary" type="button">
                  <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %>
                </button>
                <button class="btn btn-sm btn-outline-secondary" type="button">
                  <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark" %>
                </button>
                <button class="btn btn-sm btn-outline-secondary" type="button">
                  <%= link_to "注文履歴一覧", admin_orders_path, class: "btn btn-outline-dark" %>
                </button>
                <button class="btn btn-sm btn-outline-secondary" type="button">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-dark" %>
                </button>
                <button class="btn btn-sm btn-outline-secondary" type="button">
                  <%= button_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %>
                </button>
              <% else %>
                <button class="btn btn-sm btn-outline-secondary" type="button">
                  <%= link_to "About", about_path, class: "btn btn-outline-dark" %>
                </button>
                <button class="btn btn-sm btn-outline-secondary" type="button">
                  <%= link_to "商品一覧", public_root_path, class: "btn btn-outline-dark" %>
                </button>
                <button class="btn btn-sm btn-outline-secondary" type="button">
                  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %>
                </button>
                <button class="btn btn-sm btn-outline-secondary" type="button">
                  <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %>
                </button>
              <% end %>
            </div>
          </div>
        </div>
      </nav>

    </header>
    <main>
      <div id="flash-sentence">
        <% if flash[:notice] %>
          <p class="notice"><%= flash[:notice] %></p>
        <% else %>
          <p class="alert"><%= flash[:alert] %></p>
        <% end %>
      </div>

      <%= yield %>
    </main>
  </body>
</html>